const ActionType = {
  SET_LOADING: 'SET_LOADING',
  SET_REFRESH: 'SET_REFRESH',
  SET_SAVE: 'SET_SAVE',
  SET_EDIT: 'SET_EDIT',
  SET_FIRST_NAME: 'SET_FIRST_NAME',
  SET_LAST_NAME: 'SET_LAST_NAME',
  SET_AGE: 'SET_AGE',
  SET_MODAL: 'SET_MODAL',
  SET_CONTACT_DETAIL: 'SET_CONTACT_DETAIL'
};

export default ActionType;
